/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Car(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("./models/car/model.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.group2133652563.geometry}
        material={materials.mat21}
      />
      <mesh
        geometry={nodes.mesh1085046267.geometry}
        material={materials.mat23}
      />
      <mesh
        geometry={nodes.mesh1085046267_1.geometry}
        material={materials.mat13}
      />
      <mesh
        geometry={nodes.mesh1085046267_2.geometry}
        material={materials.mat15}
      />
      <mesh
        geometry={nodes.mesh1085046267_3.geometry}
        material={materials.mat16}
      />
      <mesh
        geometry={nodes.mesh1085046267_4.geometry}
        material={materials.mat3}
      />
      <mesh
        geometry={nodes.mesh1085046267_5.geometry}
        material={materials.mat17}
      />
      <mesh
        geometry={nodes.mesh1085046267_6.geometry}
        material={materials.mat12}
      />
      <mesh
        geometry={nodes.mesh1085046267_7.geometry}
        material={materials.mat24}
      />
      <mesh
        geometry={nodes.mesh1085046267_8.geometry}
        material={materials.mat8}
      />
      <mesh
        geometry={nodes.mesh1085046267_9.geometry}
        material={materials.mat25}
      />
      <mesh
        geometry={nodes.mesh1085046267_10.geometry}
        material={materials.mat14}
      />
      <mesh
        geometry={nodes.mesh1085046267_11.geometry}
        material={materials.mat21}
      />
    </group>
  );
}

useGLTF.preload("./models/car/model.glb");
