/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/desert./models/desert//model.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Desert(props) {
  const { nodes, materials } = useGLTF("./models/desert/model.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Box014.geometry}
        material={materials["07___Default"]}
      />
      <mesh
        geometry={nodes.Box025_1.geometry}
        material={materials._Cactus_46902___Default}
      />
      <mesh
        geometry={nodes.Box025_1_1.geometry}
        material={materials["09___Default"]}
      />
      <mesh
        geometry={nodes.Box025_1_2.geometry}
        material={materials["02___Default"]}
      />
      <mesh
        geometry={nodes.Box025_1_3.geometry}
        material={materials["08___Default"]}
      />
      <mesh
        geometry={nodes.Box025_1_4.geometry}
        material={materials["03___Default"]}
      />
    </group>
  );
}

useGLTF.preload("./models/desert/model.glb");
