/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ./public/models/pyramid/model.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Pyramid(props) {
  const { nodes, materials } = useGLTF("./models/pyramid/model.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pyramid.geometry} material={materials.None} />
    </group>
  );
}

useGLTF.preload("./models/pyramid/model.glb");
